### ISSUE TITLE
Is this still working?

### ISSUE THREAD

**Issue by clinton05** [andrew0/SiriusXM#5]
Has anyone tried this recently. Im having a few troubles.

**Comment by xelorz** [comment]
Worked fine. Played well in mpv.

**Comment by allanak** [comment]
Seems the API changed or something. I can't authenticate.

`± |master U:1 ✗| → python server.py
Received 403 Forbidden, renewing token
Session expired, logging in
Successfully logged in
Session expired, logging in
Successfully logged in
Session expired, logging in
Successfully logged in
Session expired, logging in
Successfully logged in
Session expired, logging in
Successfully logged in
Session expired, logging in
Successfully logged in
Session expired, logging in
Successfully logged in
Session expired, logging in
Successfully logged in
Session expired, logging in
Successfully logged in
Session expired, logging in
Successfully logged in
Session expired, logging in
Successfully logged in
Session expired, logging in
Successfully logged in
Session expired, logging in
Unable to login
127.0.0.1 - - [01/Apr/2018 18:03:50] "GET /34.m3u8 HTTP/1.1" 500 -`

**Comment by clinton05** [comment]
try serious cast

**Comment by allanak** [comment]
@clinton05 do you actually have seriouscast working?

**Comment by andrew0** [comment]
@allanak I recently updated the script for the new API and hadn't gotten around to uploading it. I just pushed the new script, give that a try.

**Comment by allanak** [comment]
@andrew0 thanks for the commit but I'm still having problems. Is this working for you?

> ± |master ✓| → python3 sxm.py user@email.com mypw 9001
> 02.Apr 2018 12:07:56 <SiriusXM>: Unable to authenticate
> 02.Apr 2018 12:07:56 <SiriusXM>: Unable to get channel list
> 02.Apr 2018 12:07:56 <SiriusXM>: No channel for 22
> 127.0.0.1 - - [02/Apr/2018 12:07:56] "GET /22.m3u8 HTTP/1.1" 500 -
> 02.Apr 2018 12:07:56 <SiriusXM>: Unable to authenticate
> 02.Apr 2018 12:07:56 <SiriusXM>: Unable to get channel list
> 02.Apr 2018 12:07:56 <SiriusXM>: No channel for 22
> 127.0.0.1 - - [02/Apr/2018 12:07:56] "GET /22.m3u8 HTTP/1.0" 500 -
> 02.Apr 2018 12:07:56 <SiriusXM>: Unable to authenticate
> 02.Apr 2018 12:07:56 <SiriusXM>: Unable to get channel list
> 02.Apr 2018 12:07:56 <SiriusXM>: No channel for 22
> 127.0.0.1 - - [02/Apr/2018 12:07:56] "GET /22.m3u8 HTTP/1.0" 500 -

**Comment by andrew0** [comment]
@allanak Are you able to login using your username instead of email? When I try to login using my email it doesn't work even on the actual SiriusXM website.

Also, there's no channel with id 22. If you're trying to access pearl jam radio, it's 8370.m3u8. The channel name's and IDs are in the readme.

**Comment by allanak** [comment]
Hmm, they are the same credentials I use for the player.siriusxm.com site so that should be ok. I'm no python expert but I might need to add some debugging to requests to see the json requests/responses or something. Thanks for the heads up on the channel numbering though.

**Comment by andrew0** [comment]
@allanak Looking at your console output it's actually not having trouble logging in, it's failing in the authenticate function, otherwise it would've said "Unable to authenticate because login failed." Can you add `print(data)` after line 126 and post the response?

**Comment by allanak** [comment]
Strangely it works now that I've added the print function. Thank you @andrew0 - can I buy you a beer?

**Comment by curzondax79** [comment]
Either @allanak or @andrew0 , when you put the print(data) after line 126, what does it look like in the file.  I've attempted to do this a couple of times, and I'm just getting syntax errors.

**Comment by curzondax79** [comment]
This has been working for me as well for several days.  Today, when I attempted to play a station, I too received a message like allanak did above where it is failing the authenticate function.  I added the print(data) function to my script and this was my output.  

python3 sxm.py username password 8888
{'ModuleListResponse': {'messages': [{'message': 'Authentication Required', 'code': 201}, {'message': 'Eligible for Open Access Trial', 'code': 106}], 'status': 1}}
06.May 2018 13:26:49 <SiriusXM>: Unable to authenticate
06.May 2018 13:26:49 <SiriusXM>: Unable to get channel list
06.May 2018 13:26:49 <SiriusXM>: No channel for 90salternative

**Comment by curzondax79** [comment]
And I just waited a bit and it started to work again.  Since nothing was different was done on my end, I wonder if SiriusXM was having some technical difficulties, especially since on the web end of the page, I did get a "we are recovering from a system error" message.  Excellent script, and this script has restored SiriusXM functionality to my Squeezebox.
